### ISSUE TITLE
Create an implementation of User filters

### ISSUE THREAD

**Issue by fluke777** [gooddata/gooddata-ruby#164]

**Comment by korczis** [comment]
@fluke777, can you confirm this is implemented already? Can we close this now?

**Comment by fluke777** [comment]
@korczis Yes, this was done in 6.12 I think?

**Comment by fluke777** [comment]
Yes this is released for some time. There are examples here https://github.com/gooddata/gooddata-ruby-examples/tree/master/11_working_with_data_filters
