### ISSUE TITLE
Dashboards story

### ISSUE THREAD

**Issue by fluke777** [gooddata/gooddata-ruby#180]
Let's create a way how to create and manipulate dashboards in a simple way so we have something.

1) Dashboards manipulation
	- I can access tabs
	- Tabs behave like objects
	- I can access the items on tabs in a sane way
2) Report creation
	- currently we have a table. Create a way how to create also Barchart, LineChart, Headline, Bubble chart. Explore the ways how the Interfaces can/cannot be the same.

3) Ability to create a dashboard programmatically
	- There is a big focus on pixel perfect design on our dashboards. This defies the purpose of accessible information. Let's not focus on how it looks but to be able to create something that looks simple programatically.
	- Define simple builder DSL to be able to create dashboards with simple grid like layout.
	- Simplify as much as possible. There is a lot of things to tune on a visual side of things. If you are not sure as a rule of thumb use this "UI should work hard on making it pretty not us".

**Comment by korczis** [comment]
Done: https://jira.intgdc.com/browse/BIA-166
