### ISSUE TITLE
Global retry on Gooddata calls

### ISSUE THREAD

**Issue by adriantoman** [gooddata/gooddata-ruby#181]
I think that it would be nice to specify the number of retries for each GoodData call globaly. For example if there is some performance problem on platform, I want to add there some automatic retry. This would help me to create reliable tools without much coding.

This can be specified on connection level or on global level.

I am now using something like this:

    def self.retryable
      begin
        tries ||= 3
        yield
      rescue => e
        if (tries -= 1) > 0
          @@log.warn "There was error during operation: #{e.message}. Retrying"
          retry
        else
          @@log.error e.message
          fail e.message
        end
      end
    end

And usage looks like this:
response = Helper.retryable do
            GoodData.get("/gdc/projects/#{s.r_project}/schedules/#{s.gooddata_schedule}/executions")
          end

**Comment by korczis** [comment]
Solved in #344
