### ISSUE TITLE
connection.upload only accepts local files

### ISSUE THREAD

**Issue by desheikh** [gooddata/gooddata-ruby#23]
The upload method only accepts File objects, but when attempting to upload remote files using URLs (ie. Gooddata.upload(open('http://path.com')) ), the process can fail if the file size is under 10 KB. Ruby converts these files to StringIO objects which the Gooddata gem cannot use. 
On line 252 of connection.rb: 
:payload => File.read(file)
should accomodate for all: path_names, File and StringIO objects

**Comment by korczis** [comment]
Created: https://jira.intgdc.com/browse/BIA-186
