### ISSUE TITLE
Update Documentation Examples, get_dataset --> find_dataset, find_dataset_by_title, upload

### ISSUE THREAD

**Issue by thnkr** [gooddata/gooddata-ruby#244]
## Description
Outdated documentation for method on blueprint. ".get_dataset", and ".upload" methods throw no method error.

## Repeat
- Jack in to project. 
- blueprint.get_dataset("BBB") --> throws no method error.
- Change to .find_dataset("BBB") --> Returned dataset "BBB".

http://sdk.gooddata.com/gooddata-ruby/reference/ref-loading-data/

**Comment by fluke777** [comment]
Works as expected in 0.6.18
