### ISSUE TITLE
Support for scheduled exports

### ISSUE THREAD

**Issue by adriantoman** [gooddata/gooddata-ruby#293]
Hi

I think it would be nice to have support for scheduled report exports in Ruby SDK.

http://docs.gooddata.apiary.io/ -> Reports and Dashboards by Email

It would be nice to have collection of all already created Exports on project level. It would be nice to enable edit, delete and new use case on this resource.

Please let me know if you need any more info.

Adrian

**Comment by korczis** [comment]
Created: https://jira.intgdc.com/browse/BIA-177
