### ISSUE TITLE
metric.pretty_expression fails on nonexisting element

### ISSUE THREAD

**Issue by fluke777** [gooddata/gooddata-ruby#300]
Please do not fail and fill the missing value with '(empty value)' similar to what our UI does.

**Comment by korczis** [comment]
Solved in #342, closing.

**Comment by fluke777** [comment]
Sorry, just on last Thursday I found another case that we did not cover. https://github.com/gooddata/gooddata-ruby/pull/407

**Comment by fluke777** [comment]
Closing
