### ISSUE TITLE
Feature request: work with grf files

### ISSUE THREAD

**Issue by baskoj** [gooddata/gooddata-ruby#330]
Hi,

As I discussed with main Ruby developer. We support upload, schedule and graph execution. We do not support work with grf files now.

Customer's case (https://gooddata.zendesk.com/agent/tickets/47230):

1) Add the attribute/fact to my dataset.
2) Publish the model to the server
3) Update my query from where value of added attribute/fact is coming in grf file.
4) Update metadata in DB Input table and map these field to GD dataset writer.
5) Deploy this project to server.

We are able to cover points 1 and 2. No support for 3 and 4...

Could you, please, analyse the request.

Thank you,
Honza Basko

**Comment by fluke777** [comment]
Hey @baskoj 

Supporting generating CC graphs are beyond the scope of GoodData SDK. The scenario describe above is definitely possible but it is about interplay of several pieces. There is functionality for uploading data from SDK which can be generated.
