### ISSUE TITLE
Cascaded delete when possible

### ISSUE THREAD

**Issue by korczis** [gooddata/gooddata-ruby#334]
When deleting report (for example) it will be nice to have deleted all dependencies as well - report definitions, metrics if specified ... r.delete({ :cascaded => true })

This can be done using #usedby, see https://github.com/gooddata/gooddata-ruby/blob/master/spec/integration/full_project_spec.rb#L154..L157

**Comment by fluke777** [comment]
@korczis Tomas, any comments?

**Comment by fluke777** [comment]
Closing for now. Report is deleted in a cascading manner (+ definitions). Otherwise it rarely makes sense.
