### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by fluke777** [gooddata/gooddata-ruby#338]
Polling is currently implemented fairly well imho but it could be better. There are couple of libraries liying around that could help us with implementing exponential back offs during polling.

**Comment by korczis** [comment]
[retries](https://github.com/ooyala/retries) looks most complete.

**Comment by fluke777** [comment]
I am closing this.

Pollers were reimplemented that they are all handled through common handler. They accept time_limit from outside to allow better use of this for outside devs (this is coming in new release). They automatically handle retries on 429 and 503. I do not think there is any backlog for those right now.
