### ISSUE TITLE
Lint crash - issue with fiscal dates?

### ISSUE THREAD

**Issue by aaronmyhre** [gooddata/gooddata-ruby#362]
issue: lint crashes on project
project qnusqxp5c73724yr6ki5sndjqrzsm99t
issues: looks like lint doesn't like fiscal dates...

Log:
Enter Project ID for LINT:
qnusqxp5c73724yr6ki5sndjqrzsm99t
Running LINT on "Nuance - Bookings Analytics test for lint"...
/Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:103:in `find_dataset': Dataset I_FDATE_DIM.fiscalOct1_dt could not be found (RuntimeError)
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:227:in `find_dataset'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:294:in `block in referenced_by'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:293:in `map'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:293:in `referenced_by'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:400:in `block in find_star_centers'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/extensions/enumerable.rb:6:in `call'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/extensions/enumerable.rb:6:in `block in mapcat'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/extensions/enumerable.rb:5:in `each'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/extensions/enumerable.rb:5:in `reduce'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/extensions/enumerable.rb:5:in `mapcat'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:400:in `find_star_centers'
	from /Users/aaronmyhre/.rvm/gems/ruby-2.1.2/gems/gooddata-0.6.10/lib/gooddata/models/project_blueprint.rb:355:in `lint'
	from lint.rb:12:in `<main>'

**Comment by korczis** [comment]
Fixed in #364, closing.
