### ISSUE TITLE
Export data to HTML table

### ISSUE THREAD

**Issue by alespouzar** [gooddata/gooddata-ruby#380]
I would appreciate to have option to export data (e.g. array of arrays/hashes) to something more readable than just plain text/CSV. Some method for exporting data to HTML & CSS table would be nice. There's existing gem for it: https://rubygems.org/gems/html-table but it requires some coding.

HTML is more interactive (hyperlinks; e.g. to reports/metrics) and CSS formatting can make everything more readable. One customer wanted a list of all reports in a project (500+) with information when they were created/updated to check which reports can be removed. CSV file wouldn't be much helpful because you can't simply click on hyperlink to see a report.

**Comment by korczis** [comment]
Created: https://jira.intgdc.com/browse/BIA-179

**Comment by zsvoboda** [comment]
This is out of scope of the current SDK
