### ISSUE TITLE
Incosistent behavior for report.execute

### ISSUE THREAD

**Issue by vpasler** [gooddata/gooddata-ruby#384]
I am executing 2 different reports with the following code:
GoodData::Report.find_by_title(report_title, :client => client, :project => p).map do |reprt|
		result = reprt.execute
		puts result.class
		print result.column_headers
end
The results I am getting are as follows... if the report has only 1 column, the column_headers method doesn't give the expected results which leads to the inability to reuse the code on all reports in the same way. 

Report with only 1 column:
![screen shot 2015-01-13 at 15 01 51](https://cloud.githubusercontent.com/assets/6614084/5721716/2e17ee92-9b35-11e4-83f9-7b828f2d248f.png)
GoodData::ReportDataResult
[[nil]]	

Report with more than 1 column:
![screen shot 2015-01-13 at 15 02 03](https://cloud.githubusercontent.com/assets/6614084/5721715/2df7c946-9b35-11e4-979d-4059fe59c65f.png)
GoodData::ReportDataResult
[["Spend"], ["Impressions"]]

**Comment by fluke777** [comment]
@korczis , @vpasler 

Data result code was one of the oldest in SDK from me so I reimplemented it. The API is slightly different but it should be more flexible and hopefully readable. There are tests for the code including one line eample from above.

https://github.com/fluke777/gooddata-ruby/tree/report_reimplementation

**Comment by fluke777** [comment]
Fixed by https://github.com/gooddata/gooddata-ruby/pull/559
