### ISSUE TITLE
method #add_fact allways creates facts with datatype INT

### ISSUE THREAD

**Issue by mhauzirek** [gooddata/gooddata-ruby#389]
When I create fact in blueprint using add_fact method, the datatype is set to INT while default for facts in GoodData is DECIMAL(12,2). This is kind of confusing because everything goes OK until dataload.

I tried this but the fact was created as INT again:
d.add_fact(name,{:title => "Fact Title", :dataType => "DECIMAL(12,2)"})

**Comment by fluke777** [comment]
Ruby uses something called snaked case so somethingType should be correctly written as something_type. 

That being said the type in GD can be overriden like this

    gd_data_type": "DECIMAL(12,2)"

The default change (to DECIMAL) is already implemented in another branch and will be in upcoming release.
