### ISSUE TITLE
GoodData schedule not saved even if parameters were changed

### ISSUE THREAD

**Issue by alespouzar** [gooddata/gooddata-ruby#394]
I need to update ETL schedule parameters. I'm using this code:

p.schedules.each do |s|
    s.params["S3_ACCESS_KEY"] = "ABCDEFGH"
    s.save
end

Even if the object is updated, @dirty is still 'false' and schedule is not updated. After discussion with Tomas Korcak, we see two solutions:

1) Fix the method so it is able to recognize every single change inside the hash (object)
2) Add some "force save" feature (method save!) that will update a schedule (object in general) even if @dirty is false.

**Comment by korczis** [comment]
Third option is dirty caching completely, but I am against it ;-)

**Comment by korczis** [comment]
Ad 1) this should not be so difficult, we can check the checksum of the json serialized to string and do the save only of it the checksum of json has changed.

**Comment by fluke777** [comment]
@korczis 

Why do not we just use #set_param(k, v) which sets particular key?

**Comment by alespouzar** [comment]
Any progress here?

**Comment by fluke777** [comment]
@alespouzar Can you confirm that the solution mentioned above would work for you?

**Comment by alespouzar** [comment]
@fluke777  Not sure how to use this method. Can you provide an example? Thanks.

**Comment by fluke777** [comment]
@alespouzar 

When you are using this code

    p.schedules.each do |s|
        s.params["S3_ACCESS_KEY"] = "ABCDEFGH"
        s.save
    end

the fundamental problem is that when you do

    s.params["S3_ACCESS_KEY"] = "ABCDEFGH"

technically you are not communicating with the schedule object but with the Hash object. The schedule does not get a chance to notice somebody changed it. There are couple of ways how to fix that. The easiest way is to provide you with a set_param method. Your code would then look like this

    p.schedules.each do |s|
        s.set_param("S3_ACCESS_KEY", "ABCDEFGH")
        s.save
    end

Notice that now you are communicating directly with schedule object. The implementation of set_param would be something like

    def set_param(key, val)
      s.params[key] = val
      @dirty = true
    end

Let me know if this helped

**Comment by fluke777** [comment]
Solved as part of https://github.com/gooddata/gooddata-ruby/pull/528
