### ISSUE TITLE
Link and Comment data types missing

### ISSUE THREAD

**Issue by sl4dy** [gooddata/gooddata-ruby#399]
Special data types for Link and Comment (as it is in Clover) are missing in SDK

**Comment by fluke777** [comment]
@sl4dy The reason they are missing is I could not find comprehensive list of the supported types. Could you point us to one?

**Comment by korczis** [comment]
They are briefly described at page 351 in [this document](http://help.gooddata.com/doc/public/pdf/GoodData%20Reference%20Guide.pdf)
