### ISSUE TITLE
including terminal-table breaks activerecord queries

### ISSUE THREAD

**Issue by desheikh** [gooddata/gooddata-ruby#404]
As referenced in https://github.com/tj/terminal-table/issues/47, terminal-table monkeypatches the ruby String class, which breaks activerecord queries. This prevents us from using gooddata-ruby in our rails app.

**Comment by fluke777** [comment]
Hey @desheikh sorry for later response. This is unfortunate. I see not response from terminal-table team. We are currently working on fixing some smaller issues. We will let you know how we decide about proceeding. By any chance do you understand the reason why they aliase String#ljust, to left?

**Comment by desheikh** [comment]
Hi @fluke777, the alias just seems to be for cosmetic reasons, the fix seems pretty simple but I haven't been able to get the test suite to run though.

I'm working off a fork which removes the cli dependencies for now. It feels that functionality could really just be split off to a separate gem.

**Comment by fluke777** [comment]
@desheikh Comsetic reasons are the worst :-) We can prepare the fix the question is if the author will merge it. Worst case we will remove the dependency. Hopefully there is something out there that does something similar.

**Comment by nateberkopec** [comment]
This is fixed on master in terminal-table. I should have a release out soon.

**Comment by korczis** [comment]
@nateberkopec Thank you for info, do you have any idea when new version could get released?

**Comment by korczis** [comment]
Related to https://github.com/tj/terminal-table/pull/45

**Comment by nateberkopec** [comment]
Sorry, I don't - what you see in that issue thread is all I know.

**Comment by fluke777** [comment]
I am closing this. We updated to the latest version recently. Thanks everybody who helped to get the new  release of terminal-table out.

**Comment by nateberkopec** [comment]
:tada:
