### ISSUE TITLE
polling for status doesn't timeout if the gooddata task never completes

### ISSUE THREAD

**Issue by desheikh** [gooddata/gooddata-ruby#408]
When calling project.export_clone(data: false, users: false), as long as the polling status keeps returning 'RUNNING' the job will never time out.

We just ran into an issue with gooddata, where our export was never completing, resulting in our background jobs server being bottlenecked by all the project export jobs.

Ideally polling should just throw an exception after a reasonable period of time has passed by and the status has not changed.

**Comment by fluke777** [comment]
Hi @desheikh 

In upcoming release you will be able to pass your own limit into async tasks so the "waiting" is interrupted. This still does not cancel the async task but allows you to decide what to do next. Simple example is here https://github.com/gooddata/gooddata-ruby-examples/blob/master/01_getting_started/11_using_asynchronous_tasks.asciidoc

Let me know if this helps
