### ISSUE TITLE
Add folder support to blueprints (customer requested feature)

### ISSUE THREAD

**Issue by Tereci** [gooddata/gooddata-ruby#409]
Mavenlink uses blueprints for dynamic LDM manipulation. They need to be able to define folders for attribtues/facts etc. E.g. in CC there is a folder automatically created for every dataset and all attributes/facts of that dataset are automatically assigned to that folder. Without this feature it is very hard to find the attributes you need when creating reports in the UI as there are hundreds of them.

**Comment by fluke777** [comment]
This was done and released in 0.6.18 version. There are examples in https://github.com/gooddata/gooddata-ruby-examples/blob/master/12_working_with_blueprints/10_work_with_folders.asciidoc

The only thing not implemented from the example is giving a dataset custom title. This is coming shortly.
