### ISSUE TITLE
Add hostname parameter support to 'gooddata auth store'

### ISSUE THREAD

**Issue by id027** [gooddata/gooddata-ruby#418]
See subj - it would make life easier when working with whitelabeled environments.

**Comment by fluke777** [comment]
Hey @id027 

Just to clarify. Do you mean that you would like to by default connect to different server?

**Comment by id027** [comment]
Yes, exactly.

**Comment by fluke777** [comment]
@korczis This was probably solved recently right?

**Comment by korczis** [comment]
@id027 @fluke777 Yop!
