### ISSUE TITLE
TypeError: can't convert StringIO into String

### ISSUE THREAD

**Issue by randycoulman** [gooddata/gooddata-ruby#420]
When an error occurs during upload, an error `TypeError: can't convert StringIO into String` occurs.

A StringIO instance is created here: https://github.com/gooddata/gooddata-ruby/blob/master/lib/gooddata/models/model.rb#L129

and ultimately finds its way to here: https://github.com/gooddata/gooddata-ruby/blob/master/lib/gooddata/rest/connection.rb#L192

However, `StringIO` is not a subclass of `IO`, so `where.is_a?(IO)` returns false and the else clause attempts to open a file instead resulting in the error.

/cc @jackwilsonv

**Comment by korczis** [comment]
Hi @randycoulman,
first of all, I am sorry for late reply.

Thank you for reporting this. Good news is that this will be fixed very soon. 

Related to https://github.com/gooddata/gooddata-ruby/pull/413

**Comment by korczis** [comment]
Fixed in https://github.com/gooddata/gooddata-ruby/pull/433
