### ISSUE TITLE
Bug: report.export broken in 0.6.18

### ISSUE THREAD

**Issue by djiangc** [gooddata/gooddata-ruby#496]
Hi,

I ran into the following bug in 0.6.18

irb
irb(main):001:0> require 'gooddata'
=> true
irb(main):002:0> client = GoodData.connect('user, 'password')
=> #<GoodData::Rest::Client:2166 object_id: 2166>
irb(main):003:0> project = client.projects('pid')
=> #<GoodData::Project:0x4dd4965a ...
irb(main):004:0> report = project.reports.first
=> #<GoodData::Report:0x7831d1aa ...
irb(main):005:0* report.export(:csv)
ArgumentError: No :client specified
	from /Users/djiang/.rbenv/versions/jruby-9.0.0.0-pre1/lib/ruby/gems/shared/gems/gooddata-0.6.18/lib/gooddata/core/rest.rb:124:in `poll_on_code'
	from /Users/djiang/.rbenv/versions/jruby-9.0.0.0-pre1/lib/ruby/gems/shared/gems/gooddata-0.6.18/lib/gooddata/models/metadata/report.rb:125:in `export'
	from (irb):6:in `evaluate'
	from org/jruby/RubyKernel.java:990:in `eval'
	from org/jruby/RubyKernel.java:1300:in `loop'
	from org/jruby/RubyKernel.java:1110:in `catch'
	from org/jruby/RubyKernel.java:1110:in `catch'
	from /Users/djiang/.rbenv/versions/jruby-9.0.0.0-pre1/bin/irb:13:in `__script__'

The same code works in 0.6.16

Thanks,

Dong

**Comment by djiangc** [comment]
Any updates?
Anyone is following up here?

**Comment by fluke777** [comment]
Hey @djiangc. Yes we are here I just did not want to post anything until I am able to investigate.

**Comment by fluke777** [comment]
I can confirm the error on .18. It seems like it works again on develop branch. I will add an integration test to cover export as well.

**Comment by fluke777** [comment]
https://github.com/gooddata/gooddata-ruby/pull/499
