### ISSUE TITLE
Problem in lib/gooddata/rest/client.rb

### ISSUE THREAD

**Issue by adriantoman** [gooddata/gooddata-ruby#523]
I think there is bug in the following file.

The method:

```ruby
    def get_user_webdav_url(options = {})
        p = options[:project]
        fail ArgumentError, 'No :project specified' if p.nil?

        project = options[:project] || GoodData::Project[p, options]
        fail ArgumentError, 'Wrong :project specified' if project.nil?

        u = URI(project.links['uploads'])
        us = u.to_s
        ws = options[:client].opts[:webdav_server]
        if !us.empty? && !us.downcase.start_with?('http') && !ws.empty?
          u = URI.join(ws, us)
        end

        URI.join(u.to_s.chomp(u.path.to_s), '/uploads/')
      end
```

In EU datacenter the project['uploads'] setting is blank. I would like to put the webdav url by parameter webdav_server, but in current state of method it is not possible. Also I don't see any use-case where the webdav_server parameter will be used correctly in current implementation.

The project['uploads'] mostly have something like this inside: https://secure-di.gooddata.com/project-uploads/pid/". If you join this with webdav_server you will not be able to create meaningful URL. 

Can you change the method in the way, that you will use guessing from project['uploads'] key if webdav server is blank or use the webdav_server setting in case that it is present?

**Comment by korczis** [comment]
This was fixed in the past, please check this with latest version of SDK and feel free to reopen this if needed.
