### ISSUE TITLE
Make pry dependency less strict

### ISSUE THREAD

**Issue by desheikh** [gooddata/gooddata-ruby#536]
Our rails app includes gems which has a higher pry dependency.
I'm not sure why pry is locked to that specific version, but would it be possible to either bump up or make the version lock less strict?

**Comment by fluke777** [comment]
@desheikh We had some issues with higher versions so we locked it down (we are using pry as a non dev dependency also). We will reinvestigate and make the dependency less strict if possible.

**Comment by fluke777** [comment]
@desheikh 
Just tested it with s.add_dependency 'pry', '~> 0.10', '>= 0.10.1' and the problem persists. We are having the same problem as documented here https://github.com/davetron5000/gli/issues/196. I will investigate a little deeper once I have some time.

**Comment by korczis** [comment]
Created: https://jira.intgdc.com/browse/BIA-180
