### ISSUE TITLE
Wrong error message for import stage of partial MD export/import

### ISSUE THREAD

**Issue by Tereci** [gooddata/gooddata-ruby#538]
In lib/gooddata/models/project.rb on row 770 there is following error message defined:
"fail 'Exporting objects failed' if polling_result['wTaskStatus']['status'] == 'ERROR'"

It should say:
"fail 'Importing objects failed' if polling_result['wTaskStatus']['status'] == 'ERROR'"
as it's testing response of import API. Looks like a copy paste error.

**Comment by fluke777** [comment]
Here is a preliminary fix (https://github.com/fluke777/gooddata-ruby/commit/5060cb33dd1b01bd6d29700d344ce6990cd8803c). I fixed the messages + the methods are now throwing exceptions. The transfer also takes list of projects and makes sure the import runs in parallel.

**Comment by korczis** [comment]
Created: https://jira.intgdc.com/browse/BIA-178

**Comment by fluke777** [comment]
This was fixed in release 22
