### ISSUE TITLE
Find by tag for objects with multiple tags not working properly

### ISSUE THREAD

**Issue by jiritobolka** [gooddata/gooddata-ruby#553]
When I use following code, it works well for the case when Report has only 1 tag assigned. When report has multiple tags it doesn't work. See the example:

My report has tags: 'qa', '1.8' and when I run following command it doesn't match the report. I think it just compares all tags as one string and doesn't compare "substring" for individual tags...

<code>
tag = 'qa'
orig_reports = GoodData::Report.find_by_tag(tag, client: client, project: devel).sort_by(&:title)
</code>

Is there any other solution? Thanks!

JT

**Comment by korczis** [comment]
Created: https://jira.intgdc.com/browse/BIA-175

**Comment by fluke777** [comment]
@jiritobolka Sorry for later response I just noticed this. Feel free to bug me next time.

We have to fix the method (if that is not a problem on the API) but I think the preferred way to expres this is.

   devel.attributes.select {|r| r.tag_set.include?('qa')}.sort_by(&:title)

After last changes on API this should be fairly performant (probably little less than using dedicated API but it should be ok for most cases).

**Comment by jiritobolka** [comment]
Thanks! I will try it and let you know!

**Comment by jiritobolka** [comment]
Works great, thanks!

**Comment by fluke777** [comment]
This was fixed by https://github.com/gooddata/gooddata-ruby/pull/607. It will be in next release.
