### ISSUE TITLE
Missing check in blueprint validation

### ISSUE THREAD

**Issue by Tereci** [gooddata/gooddata-ruby#598]
Two issues not caught by blueprint.valid?:

1) I accidentally created a blueprint where the same identifier was used for facts in two different datasets. The blueprint.valid? returned true, but when trying to create a project out of the blueprint the API returned an error saying that two items cannot have the same id, which makes sense.
2) I generated the blueprint and didn't realize there are some () characters in the data which created invalid identifiers. Again the blueprint.valid? returned true but API returned error.

Blueprint with the issue:
blueprint = GoodData::Model::ProjectBlueprint.build("AuthIQTest1") do |p|
p.add_dataset('transactions_monthly') do |d|
    d.add_anchor('attr.transactions_monthly.factsof')
    d.add_fact('fact.transactions_weekly.transaction_amount')
    d.add_fact('fact.transactions_weekly.transaction_count')
  end

  p.add_dataset('transactions_weekly') do |d|
    d.add_anchor('attr.transactions_weekly.factsof')
    d.add_attribute('attr.transactions_weekly.hdr_banknet_week(monday)')
    d.add_label('label.transactions_weekly.hdr_banknet_week(monday)', reference: 'attr.transactions_weekly.hdr_banknet_week(monday)')
    d.add_fact('fact.transactions_weekly.transaction_amount')
    d.add_fact('fact.transactions_weekly.transaction_count')
  end
end

Message from API:
ERROR -- : 9RmbhaO4uCYwD3u6LajwiQ:w---TtvDBj797azsCD9g9A 400 Bad Request: {"error":{"errorClass":"com.gooddata.project.model.exception.InvalidTargetModelException","message":"Target model is invalid.: [Identifier 'fact.transactions_weekly.transaction_amount' is used by multiple objects. All identifiers have to be unique.Identifier 'fact.transactions_weekly.transaction_count' is used by multiple objects. All identifiers have to be unique.'attr.transactions_weekly.hdr_banknet_week(monday)' is not a valid identifier. Identifier has to start with a letter. Allowed characters: lowercase and uppercase letters, numbers, underscore \"_\" and dot \".\"'label.transactions_weekly.hdr_banknet_week(monday)' is not a valid identifier. Identifier has to start with a letter. Allowed characters: lowercase and uppercase letters, numbers, underscore \"_\" and dot \".\"]","component":"MSF","errorId":"5719e83c-d937-4ded-9830-0bd9a409198a","errorCode":"msf.project-model.target.invalid","validationErrors":[{"validationError":{"code":"identifier.notUnique","message":"Identifier '%s' is used by multiple objects. All identifiers have to be unique.","parameters":["fact.transactions_weekly.transaction_amount","2"],"contexts":["fact.transactions_weekly.transaction_amount","fact.transactions_weekly.transaction_amount"],"reparable":false}},{"validationError":{"code":"identifier.notUnique","message":"Identifier '%s' is used by multiple objects. All identifiers have to be unique.","parameters":["fact.transactions_weekly.transaction_count","2"],"contexts":["fact.transactions_weekly.transaction_count","fact.transactions_weekly.transaction_count"],"reparable":false}},{"validationError":{"code":"identifier.invalid","message":"'%s' is not a valid identifier. Identifier has to start with a letter. Allowed characters: lowercase and uppercase letters, numbers, underscore \"_\" and dot \".\"","parameters":["attr.transactions_weekly.hdr_banknet_week(monday)"],"contexts":["attr.transactions_weekly.hdr_banknet_week(monday)"],"reparable":false}},{"validationError":{"code":"identifier.invalid","message":"'%s' is not a valid identifier. Identifier has to start with a letter. Allowed characters: lowercase and uppercase letters, numbers, underscore \"_\" and dot \".\"","parameters":["label.transactions_weekly.hdr_banknet_week(monday)"],"contexts":["label.transactions_weekly.hdr_banknet_week(monday)"],"reparable":false}}]}}

**Comment by Tereci** [comment]
One more:

3) Following wrong ID passed through the valid? but not through API checks:
d.add_attribute('attr.account_details.')
    d.add_label('label.account_details.', reference: 'attr.account_details.')

It resulted in nothing saying error of:
E, [2015-09-22T14:25:39.358951 #1348] ERROR -- : 0dOZQU084cS1Dkq_zoUN5g:EAdKveFSMLho7HREFZUTAg 500 Internal Server Error: {"error":{
	"message": "Internal server error. Please fill in bug report with request_id='0dOZQU084cS1Dkq_zoUN5g:EAdKveFSMLho7HREFZUTAg:vUjQlxFkMuz4lM0d'"
}}

**Comment by panjan** [comment]
Added to backlog: https://jira.intgdc.com/browse/TMA-576

**Comment by panjan** [comment]
https://github.com/gooddata/gooddata-ruby/pull/1001
