### ISSUE TITLE
SmallGoodZilla.pretty_print doesn't convert all uris to its titles

### ISSUE THREAD

**Issue by sergeonito** [gooddata/gooddata-ruby#635]
SmallGoodZilla.pretty_print doesn't convert all uris to its titles if it contains same uris more than once

**STR:**
For example, we have expression:

```
exp = SELECT SUM(SELECT MAX([/gdc/md/project_id/obj/2813]) WHERE 
  ([/gdc/md/project_id/obj/2468] = 1 AND [/gdc/md/project_id/obj/2792] = 2) OR 
  ([/gdc/md/project_id/obj/2468] = 3 AND [/gdc/md/project_id/obj/2792] = 4))
```

when calling pretty_print, we will have something like:

```
SELECT SUM(SELECT MAX([ATTR)) WHERE 
  (ATTR1] = 1 AND [ATTR2] = 2) OR 
  ([/gdc/md/project_id/obj/2468] = 3 AND [/gdc/md/project_id/obj/2792] = 4))
```
- objects which were repeated are not converted

**Notes:**
The issue was found on new 0.6.25 version
Fix will be in method SmallGoodZilla.pretty_print (row:110 temp.sub!(uri, obj))
Use gsub! method instead sub!

**Comment by fluke777** [comment]
Good catch. Will fix it asap.

**Comment by vhtien** [comment]
Fix in https://github.com/gooddata/gooddata-ruby/pull/869
