### ISSUE TITLE
Not possible to use Amazon AWS SDK v2

### ISSUE THREAD

**Issue by alespouzar** [gooddata/gooddata-ruby#659]
It's not possible to use Amazon AWS SDK v2 and GoodData SDK at the same time, because GoodData SDK requires 'aws-sdk', (~> 1.45). Please update 'aws-sdk' to 'aws-sdk-v1' in Gemspec, which will allow to use both v1 and v2 versions (they have different namespaces).

**Comment by petr-tichy** [comment]
https://github.com/gooddata/gooddata-ruby/pull/674

**Comment by panjan** [comment]
We've just switched to using v2 only. Closing.

**Comment by panjan** [comment]
#943
