### ISSUE TITLE
Export a Large Report

### ISSUE THREAD

**Issue by tchiarato** [gooddata/gooddata-ruby#894]
Hey guys,

I've being working on a feature using GoodData that uses `gooddata-ruby` to execute some reports and a few of them is not computable due to the size of the result set.

It'd be great to have a method to execute a report using the [raw end-point](https://developer.gooddata.com/api#/reference/dashboards-and-reporting/export-a-report/export-a-raw-report) which export reports that are too large to be computed on the UI.

I also checked the end-point that is currently used to execute reports, and as the [documentation](https://developer.gooddata.com/api#/reference/dashboards-and-reporting/execute-a-report-or-report-definition) suggests it's deprecated. Any concerns about changing the deprecated end-point to the new end-point?

Best regards,
Thiago C

**Comment by korczis** [comment]
Hi,
unfortunately we do not have this functionality wrapped in gooddata-ruby SDK yet. I will discuss this with our PM and let you know if (and when) this functionality will be implemented. 

I will keep you informed.

**Comment by panjan** [comment]
Added to backlog: https://jira.intgdc.com/browse/TMA-575

**Comment by tchiarato** [comment]
Hi @panjan,

After adding to the backlog, how long it usually takes to be implemented?

Best

**Comment by panjan** [comment]
Hello @tchiarato,

We've identified two tasks that need to be done here. First, switch to the new API. Second, add support for raw exports. We'll do the former within the following weeks. Then I'll inform you about the ETA for the raw exports.

**Comment by panjan** [comment]
We've switched to the new API for executing reports (#1013). @hacxman, can you please add support for the `raw` endpoint?

**Comment by karlamaria** [comment]
Hi @pajan, 
Do we have any news about this issue? I saw that the last iteration was in October.

**Comment by panjan** [comment]
Hi @karlamaria, I'll see if #1034 can be merged. It should solve the issue.

**Comment by panjan** [comment]
The PR looks good but the build is failing. I will fix it now and merge ASAP.

**Comment by panjan** [comment]
PR merged (#1083) and new gem version released.

**Comment by panjan** [comment]
Reopening because documentation needs to be updated.

**Comment by tchiarato** [comment]
Awesome @panjan, thank you very much!
We'll update the gem version and try to use the new method to access the raw endpoint.

🚀

**Comment by Hahihula** [comment]
The [documentation](https://github.com/gooddata/gooddata-ruby-doc/pull/1) was added.
