### ISSUE TITLE
Looping over ObjectSpace

### ISSUE THREAD

**Issue by diclophis** [gooddata/gooddata-ruby#995]
Hello,

Could you outline the architectural decisions / requirements for this gem to loop over `ObjectSpace` as in this file: https://github.com/gooddata/gooddata-ruby/blob/2bd53792728329d380d96a8358cc734359c14fd5/lib/gooddata/rest/object_factory.rb#L29

We are running into issues with threads in this block of code and would like to investigate removing this module and using an alternative mechanism to achieve a similar result.

**Comment by panjan** [comment]
Hello @diclophis,

Big 👍  for reporting the issue. The code in question seems not to be used anymore. I've created a PR that mercilessly removes it. If everything goes well, this should go to the next release.

**Comment by diclophis** [comment]
OK great thank you
